#Created by st.Game
#https://github.com/andrii1890
#Find me at Discord: st_Game and Telegram: @Andrii1890

#Version "1.1"

networks:
  node:

services:
    one-nitro-node:
        image: 'offchainlabs/nitro-node:v3.5.6-rc.1-9a29a1e'
        user: 1000:1000
        restart: always
        stop_grace_period: 30s
        volumes:
            - '.arbitrum/:/home/user/.arbitrum'
        ports:
            - '0.0.0.0:8547:8547'
            - '0.0.0.0:8548:8548'
        command:
        - --init.url=https://snapshot.arbitrum.foundation/sepolia/nitro-pruned.tar
        - --parent-chain.connection.url=<Your L1 eth provider Execution Layer>
        - --parent-chain.blob-client.beacon-url=<Your L1 eth provider Consensus Layer>
        - --chain.id=421614
        - --http.api=net,web3,eth,debug
        - --http.corsdomain=*
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --ws.port=8548
        - --ws.addr=0.0.0.0
        - --ws.origins=*
        networks:
        - node
        logging:
          driver: json-file
          options:
            max-size: 50m
            max-file: "10"
